### ISSUE TITLE
Product Map and Thematic work areas

### ISSUE THREAD

**Issue by lin-d-hop** [openfoodfoundation/product-pipe#2]
Using product knowledge, old wishlists, Github and knowledge of the work over the past years we're attempting to create a Product Map and an understanding of some of the cross-cutting themes that guide our work.

**Comment by lin-d-hop** [comment]
[WIP here](https://docs.google.com/spreadsheets/d/11smYz0IeWupk5GRSwmuQXQPPjLpNcT21mJQMqc8Is7Q/edit#gid=1058571940)

**Comment by RachL** [comment]
Hey @lin-d-hop how do we want to share this one ? If think we reached something ready for wider feedback. Discourse post + link to the doc?

I would like people to concentrate first on the mapping. How it links to wishlist items will be a task for us afterwards. Do you agree?

The list of wishlist is great though to get examples and how the categories could look like.

**Comment by lin-d-hop** [comment]
Post on the Forum

https://community.openfoodnetwork.org/t/proposal-ofn-product-overview/2121

**Comment by jaycmb** [comment]
Miro Version of the product map, based on what´s been discussed during the wishlist mapping with an attempt to connect Shopper Side and Admin along the (high level) user journeys here:
https://miro.com/app/board/o9J_kib80B4=/#

We can also use colour codes to label which features or product areas are existing already vs. which are the ones in inception (e.g. network) or in dev as a lext step, like a living, dynamic product map 

![image.png](https://images.zenhubusercontent.com/5f2c695b310b603896851306/932ba065-acf7-420e-b326-e2704484fcba)
