### ISSUE TITLE
Google Maps platform terms of service

### ISSUE THREAD

**Issue by kirstenalarsen** [openfoodfoundation/product-pipe#39]
![image.png](https://images.zenhubusercontent.com/54b83fb37c6ccc6277a6ea46/037b0395-276e-4b28-93a9-7b90136c3bdd)

**Comment by kirstenalarsen** [comment]
nb. I have assigned @lin-d-hop and @RachL simply because you seem to know what it is, and so that we don't miss it in next product standup

**Comment by luisramos0** [comment]
3.2.3e https://cloud.google.com/maps-platform/terms
(e) No Use With Non-Google Maps. To avoid quality issues and/or brand confusion, Customer will not use the Google Maps Core Services with or near a non-Google Map in a Customer Application. For example, Customer will not (i) display or use Places content on a non-Google map, (ii) display Street View imagery and non-Google maps on the same screen, or (iii) link a Google Map to non-Google Maps content or a non-Google map.

Wonderful opportunity to get us out of Google by finishing? https://github.com/openfoodfoundation/openfoodnetwork/issues/5542
And https://github.com/openfoodfoundation/openfoodnetwork/pull/6825 will help if OSM geocoding isn't as good as google's, right?

**Comment by RachL** [comment]
@luisramos0 I'm afraid the fastest solution to that issue might be to use Google as a map rather than going towards OSM.
we have a lot on our plate (including other compliance problems) and prioritizing OSM will not be fast. It should for example include a spike of which OSM geocoder is best to use... 

Anyway the conclusion on this for now is to wait for the feedbacks by Costa Rica's team.

**Comment by rngkll** [comment]
This is the answer from google when we asked on the specific violation.

Dear Developer,

Thanks for the quick response, We review the domain we found Branding violation as our autocomplete is being used on Non-Google map ( https://www.laferia.cr/map#?query=Hyderabad,%20Telangana,%20Indi ) attached screenshot for your reference and add the google logo map and conform.

<img width="844" alt="image" src="https://user-images.githubusercontent.com/5940156/107372859-7f24c480-6aab-11eb-88ca-3e0cd263e288.png">

**Comment by RachL** [comment]
@rngkll thank you! Did they give more info on the delay or are you forced to deactivate your map right now?

**Comment by rngkll** [comment]
they keep saying we have to deactivate.

**Comment by rngkll** [comment]
If we remove "powered by google" we should be fine, is this possible?

email from google below

Dear Developer,

Thanks for the quick response, We review the domain we found Branding violation as our autocomplete is being used on Non-Google map ( https://www.laferia.cr/map#?query=Hyderabad,%20Telangana,%20Indi ) attached screenshot for your reference and add the google map and conform

Making a map by using the powered by google but it is not a google map, Please Change or remove the powdered by google logo.

Please keep us posted once it is fixed.

**Comment by RachL** [comment]
@rngkll I'm afraid removing "powered by google" won't be enough as we are using Google's geocoder. They can then blame us to not be transparent about it. We are analyzing the fastest option. Can you let them know we are working on it? If they need more reassurance, I would suggest you deactivated your map at https://laferia.cr/admin/contents/edit 

![image](https://user-images.githubusercontent.com/6525576/107616279-0b6eed00-6c4e-11eb-93ac-855175d43a42.png)

It avoids you to have to deactivate Google's API and this way you are not left with an empty map. What do you think?

**Comment by rngkll** [comment]
Thanks @RachL, we did what you recommended :)

**Comment by rngkll** [comment]
**My question to google:**
Is it OK if we just remove the "powered by Google"? or is there any other violation that we have to take care of?

Thanks :)

**Their answer:**
Dear Developer,

Making a map by using the powered by google but it is not a google map, Please Change map or remove the powdered by google logo.

**Comment by RachL** [comment]
@rngkll thanks for this further feedback. We are going to remove the branding with https://github.com/openfoodfoundation/openfoodnetwork/issues/6882 but as it is weird that this can be a solution, we will do a spike to assess which solution is the fastest to have a clean set up: using Google's map or switching completely to OSM.

We will keep you posted :+1:

**Comment by rngkll** [comment]
@RachL disabling from the UI wont work, because it only removes the link in the menu from the main page, we have do disable completely.

I asked google support to follow this issue, they should be able to comment and let us know if we continue to violate the terms.

**Comment by RachL** [comment]
@rngkll ok thanks. And removing the logo couldn't work as well. Indeed I didn't catch this the first time I read the emails, but the "powered by google" logo is actually appearing on the search dropdown. Removing it means removing Google's geocoder which would mean too much work right now. So luckily we've managed to remove OSM tile and replacing it by Google's tiles here : https://github.com/openfoodfoundation/openfoodnetwork/pull/6888

This will be available in our next release (which will be published next Monday or Tuesday).

Note that the colors of the maps do not match the usual colors (blue for the sea etc) but we didn't find an easy way to do it, if your Google support contact has any hot tips, it could be interesting :)

**Comment by RachL** [comment]
@rngkll our latest release is out and contains the removal of the OSM tile. Please deploy this release and this should help you become compliant with Google's terms and services : https://github.com/openfoodfoundation/openfoodnetwork/releases/tag/v3.5.10
