### ISSUE TITLE
Prepare Shortlist of MCFE needs for user validation and community update

### ISSUE THREAD

**Issue by jaycmb** [openfoodfoundation/product-pipe#50]
- [x] Make videos for each MCFE need that has been prioritised for Horizon 1 ( @RachL , @lin-d-hop , @tschumilas)

- [x] Capture essence of each video in a brief written description (@Jana)
- [x] Capture painpoints of videos in a written statement (@Eriol)

- [x] Doublecheck if needs have been understood correctly (brief description)  (@RachL , @kirstenalarsen, @lin-d-hop)

- [ ] Cherck if and pain point statement captures the perceived pain correctly (sync in product circle meeting)

**Shortlist of MCFE Needs + Brief Descriptions** (in table column 'Brief Description of needs')
https://www.notion.so/openfoodnetwork/Shortlist-of-Needs-Themes-738a485b1dfe404db5f02fb89c1c1dc3

**Pain point statements**
https://www.notion.so/openfoodnetwork/Notes-from-focus-problem-videos-7893ba93250f4bb8b3b8331cd63fff17

**Comment by Erioldoesdesign** [comment]
Still waiting on the last couple of videos but finally finished copy-pasting my pain statements into the table over the weekend from my [own notes](https://www.notion.so/openfoodnetwork/Notes-from-focus-problem-videos-7893ba93250f4bb8b3b8331cd63fff17)
