### ISSUE TITLE
Feedbacks on the new localization feature

### ISSUE THREAD

**Issue by RachL** [openfoodfoundation/product-pipe#51]
I'm opening this issue to collect feedbacks we get from the new localization feature that we introduced for enterprise registration.

Some ideas collected thus far:

- Place the localize button above the map / below the address:

![image](https://user-images.githubusercontent.com/6525576/119321945-71233a00-bc7d-11eb-9ac2-07bc238d82ab.png)

- Reverse country and state dropdown (you need to select a country to see states in the dropdown)

- Disabled the button as long as no address has been written or add a message saying the address is mandatory to use the localize feature

- The text explaining why a user should localize their address is very nice, but is only displayed once the user has clicked on the button. Before, the user does not know what for the button is. Maybe we could add more text on the first screen? 

![image](https://user-images.githubusercontent.com/6525576/119322361-db3bdf00-bc7d-11eb-99e7-c7158450a94c.png)

- this step does not handle all mandatory fields. Currently treated as s2: https://github.com/openfoodfoundation/openfoodnetwork/issues/7655

**Comment by VincentPotvin** [comment]
Hi all ! 
This feature works pretty well in Belgium, really great job 👍  It will help users to precisely indicate their location. 
I agree with Rachel's comment about the explaining text, it could be better if the user knows the "meaning' of the button before using it :)
