### ISSUE TITLE
Improve order states handling in OFN

### ISSUE THREAD

**Issue by jaycmb** [openfoodfoundation/product-pipe#54]
### Description

We want to simplify & improve the way how OFN handles order(, payment and shipping) states.

Steps
1. Create an overview  of the current state: Understand and document how states are used at the moment
2. Define the ideal state

Flow charts showing current way of order & payment states:
https://miro.com/welcomeonboard/JBzsPbFSkwj4it0RjfYsrTvoSV6bDZi3vDNja8udMxgDblSHbvr3WV7rCAytRyWG

**Comment by jaycmb** [comment]
Last working session with @filipefurtad0 we came up with a draft definition of the main order states (which we would like to keep), mapped across the 3 different order flows we currently have.

![image.png](https://images.zenhubusercontent.com/5f2c695b310b603896851306/c1eb94b3-0ab0-4d56-8a6f-c87315dd5868)

One thing that came up during several discussions is that it would be very useful being able to distinguish between the 3 types of orders, which is currently not possible.

We would like to understand more about the complexity of enabling this -> could be a spike for Andy

**Comment by lin-d-hop** [comment]
Awesome! I wonder if we can get a sign off on this and then add it to our developer wiki and super admin guide so that it is easy to find.

**Comment by jaycmb** [comment]
In today´s session we explored the shipment state topic.

There has been a discussion around the necessity of the shipment states of an order, which makes the order states machine more complex but we don´t know about whether it is actually needed / used 

There are 2 things we propose to get a better understanding:
A) Database for quantity of usage
B) Instance Managers for Behaviour (the why/how behind)

Notes of today, will create separate issues for A and B

![image.png](https://images.zenhubusercontent.com/5f2c695b310b603896851306/f617e70e-be08-40ef-9183-55e1d377d4f3)

**Comment by jaycmb** [comment]
> Awesome! I wonder if we can get a sign off on this and then add it to our developer wiki and super admin guide so that it is easy to find.

Yes @lin-d-hop , we were thought having another order states team session next week to 
- sign off order states
- update on shipment states insights and next steps
- spike on separating orders
