### ISSUE TITLE
[Spike] Remove MIGS payment gateway

### ISSUE THREAD

**Issue by filipefurtad0** [openfoodfoundation/product-pipe#7]
### What we should change and why (this is tech debt)

MIGS payment method is obsolete and should be removed from the OFN codebase (see discussion [here](https://openfoodnetwork.slack.com/archives/C4NDJT3FY/p1603291765051800?thread_ts=1603272008.051000&cid=C4NDJT3FY)).

### Context

This is related to openfoodfoundation/openfoodnetwork#6231 .

This first came to light when rolling out v3, where it was spotted that only very few users were using this payment method. See [comment](https://github.com/openfoodfoundation/openfoodnetwork/pull/5879#issuecomment-681125276).

### Impact and timeline

This should simplify the codebase and the upgrade from Rails 4.0 -> 4.1

**Comment by kirstenalarsen** [comment]
@mkllnk had a quick look at this and confirmed we won't lose anything valuable or useful. Remove it :)
